# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://cs291.com # the base hostname & protocol for your site

# User settings
course_number: CS291A
quarter: Fall 2023
title: Scalable Internet Services

github_username: scalableinternetservices

instructor: Dr. Shyr-Shea Chang
instructor_email: shyr-shea.chang@appfolio.com
instructor_url: https://www.linkedin.com/in/shyr-shea-chang-6426271b8/

drive_url: https://drive.google.com/drive/folders/11ZU37_a1Yc6pTBNo9uIcsCKV422Ypdyf?usp=sharing
piazza_url: https://piazza.com/ucsb/fall2022/cs291a

intro_survey: https://forms.gle/k3opDdFPjQRjWFV98
project0_submission: https://forms.gle/7Nafh5e9PM28b3H79

kramdown:
  parse_block_html: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
